SERVICE_PORT = 8003

SOLR_BASE = 'http://localhost:8983/solr'
SOLR_COLLECTION_ACCENTURE = '/dbAcc'
SOLR_COLLECTION_ACCENTURE_CRP = '/dbAcc'
SOLR_COLLECTION_TALENT = '/dbAcc'
SOLR_COLLECTION_IBM = '/dbAcc'
SOLR_SELECT = '/select?'

#Solr query parameters
DESCRIPTION_BOOSTING_VALUE = '0.001'
JOB_NO_OF_ROWS_FETCH = '20'
CANDIDATE_NO_OF_ROWS_FETCH = '250'
DISTANCE_FILTER = '3000'
